### ISSUE TITLE
error appears when i would like to use redis session

### ISSUE THREAD

**Issue by inzem77** [aio-libs/aiohttp_session#22]
The project in https://github.com/inzem77/ws-chat
```
serving on ('0.0.0.0', 8080)
Error handling request
Traceback (most recent call last):
  File "/home/inzem/sites/chat/ENV3.5/lib/python3.5/site-packages/aiohttp/server.py", line 272, in start
    yield from self.handle_request(message, payload)
  File "/home/inzem/sites/chat/ENV3.5/lib/python3.5/site-packages/aiohttp/web.py", line 87, in handle_request
    resp = yield from handler(request)
  File "/home/inzem/sites/chat/ENV3.5/lib/python3.5/site-packages/aiohttp_session/__init__.py", line 138, in middleware
    yield from storage.save_session(request, response, session)
  File "/home/inzem/sites/chat/ENV3.5/lib/python3.5/site-packages/aiohttp_session/redis_storage.py", line 48, in save_session
    with (yield from self._redis) as conn:
AttributeError: __exit__

```

**Comment by asvetlov** [comment]
What is *redis* parameter in your case?

According to [doc](http://aiohttp-session.readthedocs.org/en/latest/reference.html#redis-storage) you should use result of [yield from create_pool()](http://aioredis.readthedocs.org/en/latest/api_reference.html#aioredis.create_pool) call.

**Comment by inzem77** [comment]
i am using yield from. The error repeat.  
Entire code https://github.com/inzem77/ws-chat/blob/master/chat.py
```
@asyncio.coroutine
def create_redis_pool(host, port):
    yield from aioredis.create_pool((host, port), loop=loop)

redis = create_redis_pool('localhost', 6379)
storage = aiohttp_session.redis_storage.RedisStorage(redis)
session_middleware = aiohttp_session.session_middleware(storage)
app = aiohttp.web.Application(middlewares=[session_middleware])
```

**Comment by asvetlov** [comment]
Use `redis = loop.run_until_complete(create_redis_pool('localhost', 6379))`

**Comment by inzem77** [comment]
this is also not work

**Comment by asvetlov** [comment]
It works indeed, you should not return `None` from `create_redis_pool` coroutine also.

**Comment by inzem77** [comment]
ok. My script is working. Please you can add the example into manual.
```
import asyncio
import time
from aiohttp import web
from aiohttp_session import get_session, session_middleware
from aiohttp_session.cookie_storage import EncryptedCookieStorage
from aioredis import create_pool
from aiohttp_session import redis_storage, session_middleware

@asyncio.coroutine
def handler(request):
    session = yield from get_session(request)
    session['last_visit'] = time.time()
    return web.Response(body=b'OK')

@asyncio.coroutine
def init(loop):
    redis = yield from create_pool(('localhost', 6379))
    storage = redis_storage.RedisStorage(redis)
    session_middleware1 = session_middleware(storage)
    app = web.Application(middlewares=[session_middleware1])
    #app = web.Application(middlewares=[session_middleware(
    #    EncryptedCookieStorage(b'Thirty  two  length  bytes  key.'))])
    app.router.add_route('GET', '/', handler)
    srv = yield from loop.create_server(
        app.make_handler(), '0.0.0.0', 8081)
    return srv

loop = asyncio.get_event_loop()
loop.run_until_complete(init(loop))
try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
```

**Comment by inzem77** [comment]
Thank you!

**Comment by asvetlov** [comment]
Done
