### ISSUE TITLE
Occur error, if session save a bson.objectid.ObjectId instance.

### ISSUE THREAD

**Issue by TechBK** [aio-libs/aiohttp_session#30]
When i try do
```python
session = yield from get_session(self.request)
session['user'] = user
```
with user is a document of mongo, my program occur a error:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp_session/__init__.py", line 144, in middleware
    yield from storage.save_session(request, response, session)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp_session/cookie_storage.py", line 52, in save_session
    self._get_session_data(session)
  File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('56d07ade0686372f8e45b3f1') is not JSON serializable
```

#############################################
How do i replace json encoder with bson encoder?
https://github.com/aio-libs/aiohttp_session/blob/master/aiohttp_session/cookie_storage.py#L51

**Comment by asvetlov** [comment]
Unfortunately using custom JSON serializer is not possible in current `aiohttp_session` version.

Adding `encoder` and `decoder` params to `SimpleCookieStorage`, `EncryptedCookieStorage` and `NaClCookieStorage` makes sense.

We are already accept these params in `RedisStorage`.

I suggest moving `self._encoder` and `self._decoder` to `AbstractStorage` constructor.

The patch is very easy. 
I'll accept it without any additional test but documentation update is required (we've missed it even for `RedisStorage`, shame on me).

Any volunteers?

**Comment by asvetlov** [comment]
As workaround I suggest converting `ObjectId` to string and back manually on every access to session data but really prefer to have `encoder`/`decoder` support for every storage class.

The change deserves a new aiohttp_session release.

**Comment by TechBK** [comment]
I am happy and look forward to becoming one comtributor.
in addition, I would like to ask how to commit a contribute code?

**Comment by asvetlov** [comment]
@TechBK you should create a [Pull Request](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=github+pull+request)

**Comment by TechBK** [comment]
:smiley: ok

**Comment by TechBK** [comment]
@asvetlov hey, my friend. check Pull Request.

**Comment by BFriedrichs** [comment]
I just came across this relatively old issue. Unless I'm missing something, is there a reason why @TechBK's change was never merged? If there is a reason I suggest closing this issue otherwise I'd get a PR ready soon. (Especially since his fork looks like he basically completed it)

**Comment by asvetlov** [comment]
Sorry, but I cannot find any related PR.

**Comment by panagiks** [comment]
I think @BFriedrichs refers to #31 .

**Comment by asvetlov** [comment]
Looks like @TechBK  gave up after first review tour.
His PR need more love for polishing before merge.

**Comment by BFriedrichs** [comment]
Correct, I missed that for some reason. I haven’t really looked into how much changed since then but I can’t imagine these changes wouldn’t be still applicable.

**Comment by asvetlov** [comment]
I suggest creating a new PR from scratch and discussing it.

**Comment by muazhari** [comment]
any updates from these issue?

**Comment by muazhari** [comment]
The workaround to this issue by defining a custom JSONEncoder to ClientSession like below:

```
class BaseClient:

    async def get_client_session(self):
        return aiohttp.ClientSession(base_url=client_config.CLIENT_TRANSACTION_URL,
                                     json_serialize=lambda object: json.dumps(
                                         object,
                                         indent=4,
                                         sort_keys=True,
                                         default=str)
                                     )

```

**Comment by Dreamsorcerer** [comment]
Appears there is still no finished PR, feel free to propose one.
