### ISSUE TITLE
SimpleCookieStorage not working?

### ISSUE THREAD

**Issue by mentaal** [aio-libs/aiohttp_session#40]
First of all, apologies if this is not an issue and I'm just doing something wrong. 
Without going into the reason (that is a topic for another potential issue), I am trying to use the SimpleCookieStorage class.

I have a simple server which uses a slightly modified piece of example code. This server works just fine with the EncryptedCookieStorage but it dies when I try and use it with SimpleCookieStorage. 
Am I using the class incorrectly?

Server code below:
```python
import asyncio
import time
from aiohttp import web
from aiohttp_session.cookie_storage import EncryptedCookieStorage
from aiohttp_session import setup, get_session, SimpleCookieStorage


import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

async def handler(request):
    session = await get_session(request)
    last_visit = session.get('last_visit', 'Never')
    if last_visit == 'Never':
        message = "Welcome, I don't think you've visited here before."
    else:
        message = 'Welcome back, last visited: {} secs ago'.format(time.time() -
                last_visit)
    session['last_visit'] = time.time()

    return web.Response(body=message.encode('utf-8'))

async def init(loop):
    app = web.Application()
    setup(app, SimpleCookieStorage())
    #setup(app, EncryptedCookieStorage(b'Thirty  two  length  bytes  key.'))
    app.router.add_route('GET', '/', handler)
    srv = await loop.create_server(
        app.make_handler(), '0.0.0.0', 8080)
    return srv

loop = asyncio.get_event_loop()
loop.run_until_complete(init(loop))
try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
```

To make this code work, I can just comment the line invoking SimpleCookieStorage and uncomment the one invoking EncryptedCookieStorage.

The traceback I get when using the SimpleCookiStorage class is:

    Error handling request
    Traceback (most recent call last):
      File "c:\projects\aio-rpc\venv\lib\site-packages\aiohttp\server.py", line 285, in start
        yield from self.handle_request(message, payload)
      File "c:\projects\aio-rpc\venv\lib\site-packages\aiohttp\web.py", line 90, in handle_request
        resp = yield from handler(request)
      File "c:\projects\aio-rpc\venv\lib\site-packages\aiohttp_session\__init__.py", line 129, in middleware
        response = yield from handler(request)
      File "server.py", line 12, in handler
        session = await get_session(request)
      File "c:\projects\aio-rpc\venv\lib\site-packages\aiohttp_session\__init__.py", line 107, in get_session
        session = yield from storage.load_session(request)
      File "C:\Users\gkuhn\AppData\Local\Continuum\Anaconda3\envs\py35\lib\asyncio\coroutines.py", line 206, in coro
        res = func(*args, **kw)
      File "c:\projects\aio-rpc\venv\lib\site-packages\aiohttp_session\__init__.py", line 237, in load_session
        data = json.loads(cookie)
      File "C:\Users\gkuhn\AppData\Local\Continuum\Anaconda3\envs\py35\lib\json\__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "C:\Users\gkuhn\AppData\Local\Continuum\Anaconda3\envs\py35\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\gkuhn\AppData\Local\Continuum\Anaconda3\envs\py35\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mentaal** [comment]
Sorry! Turns out is wasn't an issue, I think the browser was sending the previously encrypted cookie which was trashing the server. By clearing the cookies from the browser, it works fine
